### ISSUE TITLE
Error While Executing buildHelicsInterface.m

### ISSUE THREAD

**Issue by StormsHalted** [GMLC-TDC/matHELICS#2]
Afternoon,

I get this error when running the buildHelicsInterface.m script:

>> buildHelicsInterface

Error using matlab.io.internal.archive.core.builtin.extractArchive
Invalid TAR file /home/ali/Downloads/matHELICS-main/helicsTar.tar.gz.

Error in untar (line 84)
            files = matlab.io.internal.archive.core.builtin.extractArchive(tarFilename, outputDir, 'tgz');

Error in buildHelicsInterface (line 32)
    untar('helicsTar.tar.gz');

**Comment by nightlark** [comment]
This past Friday we were looking at an issue with the Matlab untar command
on macOS not handling symlinks at all. Based on the error you got, I’d
guess that symlinks are the reason it is saying the tar file is invalid
(which explains why it works on Windows which doesn’t have symlink
support), or it can’t handle compressed tar archives; either way it seems
like Matlab’s built-in `untar` command is even more broken on Linux.

**Comment by StormsHalted** [comment]
So how to resolve this?

**Comment by nightlark** [comment]
Since you’re on HELICS 2, this part probably isn’t relevant.

The workaround is to download the helics tar file manually, and extract it
from the command line using the usual `tar -xf` system command. Then modify
the matlab build script to use that manually extracted directory instead.
